# Python Asssignment 4

1a.) what is 4 dimension? show example

An array that has 3-D arrays (matrices) as its elements is called 4-D array.



In [1]:
import numpy as np
arr = np.array([[[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]],[[[24,25,26,27],[28,29,30,31],[32,33,34,35]],[[36,37,38,39],[40,41,42,43],[44,45,46,47]]]])

print(arr)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


1b.) Reshape(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,16,17,18,19,20])

newarr = arr.reshape(4,5)

print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
2. Solve (1,2,3,4)^2     (3,2,3,4)      (1,1,1,1)
         (2,2,2,2)    x  (2,3,1,2)   +  (2,2,2,2)
         (1,1,1,1)       (2,3,3,3)      (3,3,3,3)

In [6]:
x=np.array([[1,2,3,4],[2,2,2,2],[1,1,1,1]])
y=np.array([[3,2,3,4],[2,3,1,2],[2,3,3,3]])
z=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
(x**2)*(y)+(z)

array([[ 4,  9, 28, 65],
       [10, 14,  6, 10],
       [ 5,  6,  6,  6]])

3a.)Given ([[[[[1,2,3,4], [5,6,7,8],[[9,10,11,12 [13,14,15,16]]]]])


In [1]:
import numpy as np

arr = np.array([[[[[1,2,3,4], [5,6,7,8]],[[9,10,11,12]] , [[13,14,15,16]]]]])
print(arr)



[[[list([[1, 2, 3, 4], [5, 6, 7, 8]]) list([[9, 10, 11, 12]])
   list([[13, 14, 15, 16]])]]]


In [ ]:
#3b.  From above add 3,7,10 and 16

In [11]:
import numpy as np
arr = np.array([[[[[1,2,3,4], [5,6,7,8]], [[9,10,11,12]], [[13,14,15,16]]]]])
print((arr[0,0][0][0][2]) + (arr[0,0][0][1])[2] + (arr[0][0][1][0][1] +(arr[0][0][2][0][3])))

36


3c.)What is dimension 3a called?

In [12]:
import numpy as np
arr = np.array([[[[[1,2,3,4], [5,6,7,8]], [[9,10,11,12]], [[13,14,15,16]]]]])
print(arr.ndim)

# it is called a 3-D array

3


4a.)create an array with dimension 11 using the formula

In [28]:
import numpy as np
arr = np.array([2,4,6,8,10,12],ndmin = 11)

print(arr)
print('Number of dimensions:',arr.ndim)

[[[[[[[[[[[ 2  4  6  8 10 12]]]]]]]]]]]
Number of dimensions: 11


4b.) in your own words what is numpy,explain the process of using numpy(from installation to importation with example)

Numpy is a powerful python library used for numerical and scientific computing.numpy core features includes:

    1.Efficient arrays(ndarray) for fast computation
    
    2.Mathematical operations like sum,mean,matrix multiplication etc.
     
    3. Multi-dimensional data structures-1D,2D,3D e.t.c
     
    4.It is also used in machine learning,data science,statistics and engineering
    


### process of using numpy from installation to importation with examples

1.) Install numpy(if not already installed)
Install it using this command: C:\Users\Your Name>pip install numpy
        
2.) Import numpy before using it
import numpy as np

3.)Create a numpy Array
arr = np.array([1,2,3,4,5])

4.)Reshape Arrays
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21,23])

newarr = arr.reshape(4, 3)

print(newarr)


5.)Real-world Application:
    numpy is often used with:
    1. Data science-- Handling large datasets
    2. Machine learning-- feeding input arrays to models
    3. statistics-- Mean,standard deviation, distribution


In [ ]:
#5a. Arrange the following into python array 
#(a). (4,1,2,3  )       (b). (2,3,4,5)(2,3,4,5)       (c). (2,3,4,5)
#     (3,2,4,5  )            (2,2,2,2)(3,4,5,6)            (2,3,0,1)
#     (2,5,6,7  )            (0,0,0,0)
#     (8,9,10,11)            (1,1,1,1)

In [9]:
import numpy as np

arr = np.array([[4,1,2,3],[3,2,4,5],[2,5,6,7],[8,9,10,11]])
print(arr)

[[ 4  1  2  3]
 [ 3  2  4  5]
 [ 2  5  6  7]
 [ 8  9 10 11]]


In [14]:
#5b. ([2,3,4,5],[2,2,2,2],[2,5,6,7],[8,9,10,11])
import numpy as np
arr = np. array([[2,3,4,5],[2,2,2,2],[0,0,0,0],[1,1,1,1]])
arr2 = np.array([[2,3,4,5],[3,4,5,6]])
print(arr)
print(arr2)

[[2 3 4 5]
 [2 2 2 2]
 [0 0 0 0]
 [1 1 1 1]]
[[2 3 4 5]
 [3 4 5 6]]


In [15]:
#5c. ([2,3,4,5],[2,3,0,1])
import numpy as np

arr = np.array([[2,3,4,5],[2,3,0,1]])
print(arr)

[[2 3 4 5]
 [2 3 0 1]]


6a.) How do we check for dimensions using formula?

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10],ndmin = 7)

print(arr)
print('Number of diminsions:',arr.ndim)

6b.) Show example using 5D array

In [32]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10],ndmin = 5)

print(arr)
print('Number of diminsions:',arr.ndim)

[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]
Number of diminsions: 5


7.) what do we use to check for rows and column in data array? show example

shape is used to check the number of rows and columns of data shape is used to check the number of rows and columns of data

In [34]:
import numpy as np

arr = np.array([[2,3,4],[1,2,3],[5,5,6]])

print(arr.shape)

(3, 3)


8. numpy.array((1,2,3)) == [1,2,3] ... Explain why

In [11]:
import numpy
a=numpy.array((1,2,3))
print(a)

# numpy converts tuples and list into arrays the same way and this is because numpy treats both as sequential data
# and creates identical 1D array

[1 2 3]


9. What is the difference between copy and view? with example

The difference between copy and view is that the changes made in copy does not affect the original while changes made in view affects the original

In [12]:
# example of copy

import numpy as np
arr = np.array([2,4,6,8,10])
x = arr.copy()
arr[0]=20

print(arr)
print(x)

[20  4  6  8 10]
[ 2  4  6  8 10]


In [16]:
# example of view

import numpy as np
arr = np.array([2,4,6,8,10])
x = arr.view()
arr[0]=20

print(arr)
print(x)

[20  4  6  8 10]
[20  4  6  8 10]


10a. What is alias


  

AN alias allows you to assign a custom name to a field in your data set,using 'AS' statements

  b.why is np.array(42) called a scalar

It is called scalar because it has no axes- just a single value making it a 0-D array also called a scalar.